language: python
cache: apt
sudo: false
addons:
  apt:
    packages:
    - language-pack-en-base
branches:
  only:
  - src
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_deb295246fe2_key -iv $encrypted_deb295246fe2_iv
  -in id_rsa.enc -out id_rsa -d
- git config --global user.name 'MRITYUNJAY CI'
- git config --global user.email 'mjay.cse@gmail.com'
- git config --global push.default 'simple'
- pip install --upgrade pip wheel
- echo -e 'Host github.com\n    StrictHostKeyChecking no' >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git remote rm origin
- git remote add origin git@github.com:mrityunjaykumar911/blog.git
- git fetch origin master
- git branch master FETCH_HEAD
install:
- pip install --upgrade git+https://github.com/getnikola/nikola#egg=Nikola
- pip install --upgrade git+https://github.com/ionelmc/python-ghp-import
script:
- nikola build && nikola github_deploy -m 'Nikola auto deploy [ci skip]'
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: iAaKOSMPTT1ZunBmeWhU5NEgwV30GBVRF6mWN4zuO/BaCZBRlKxdUTzk2cg18Q2mCT5ucyzfnua6pADbRHmWRoEDy7Fw9zgbkHnQAFP1865zpttiGU7oCIAlrwY+b6kjQgp9v9GgwIFmUigMJU1uoeTwaZrz9qx6oeleE2J68dRqX/x64QThyweSbBT3eoh0fuSH/mdkUsybqORrwTDZgLvgQ7IC6A/p5wqcDZAJ0MDL8p05GxC8xGHYLdsreNAUZfw767QiWXqvoLXqHa8B0JJfsgqIgT9IA0k6/b07KiZ0GxL7DIoVtdvZd4Xv362cHHQAHEb59Myp1Zc/AQ3vcOO/08s579utyI+/AHnFFgv87SVd+NYvskc7b8mMsi0Z6pyHRl7UmATtikA+3ZSeg80UL4C+DL7SOU5m1DW7haPy3o4Jfn+Mi2GxZvPX4KpihUexmNfZkwEn68DuxFsSsTASnz1tEayhwj1F20UMHlecedFslboRgY7uH6g1XfYhWe76KJnR+31RvsG1Ey8C6m8ZObw5gYpT5EIMN2HE2S2KU3xz/ebOfQstySdb2ZsiZfGxAI0NcctxN3brXLXGjkBMhLUGrRt33xTTjRlhogy61hhnaeugXk+mWF8z94ModuP6hqbVDTdASxLnlbHQQS7LeR+aMlNs5wE9fMDTOo4=
  app: mjay-blog
  on:
    repo: mrityunjaykumar911/blog
    branch: src
