language: python
cache: apt
sudo: false
addons:
  apt:
    packages:
    - language-pack-en-base
branches:
  only:
  - src
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_deb295246fe2_key -iv $encrypted_deb295246fe2_iv
  -in id_rsa.enc -out id_rsa -d
- git config --global user.name 'MRITYUNJAY CI'
- git config --global user.email 'mjay.cse@gmail.com'
- git config --global push.default 'simple'
- pip install --upgrade pip wheel
- echo -e 'Host github.com\n    StrictHostKeyChecking no' >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git remote rm origin
- git remote add origin https://github.com/mrityunjaykumar911/blog.git
- git fetch origin master
- git branch master FETCH_HEAD
install:
- pip install --upgrade git+https://github.com/getnikola/nikola#egg=Nikola
- pip install --upgrade git+https://github.com/ionelmc/python-ghp-import
script:
- nikola build && nikola github_deploy -m 'Nikola auto deploy [ci skip]'
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key: c2bb5939-0daf-4f5f-a9f8-e92f6d36c03b
  app: mjay-blog
  on:
    repo: mrityunjaykumar911/blog
    branch: src
